# place project specific paths in variables to make the rest of the script more generic
variables:
  NUPKG_FOLDER: 'RapidSoft.Micro.Throttle/bin/Release'

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet build ETLBox.sln -c Release
  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - "$NUPKG_FOLDER/"

test_job:
  stage: test
  script:
    - dotnet test RapidSoft.Micro.Throttle.Tests/RapidSoft.Micro.Throttle.Tests.csproj
