variables:
  # Opt out of telemetry (turbo and others), see https://consoledonottrack.com/
  DO_NOT_TRACK: 1
  # Enable debug services
  CI_DEBUG_SERVICES: "true"
  # Enable service network
  FF_NETWORK_PER_BUILD: "true"
  # Nupkg folder
  NUPKG_FOLDER: ".packages"
  # avoid shallow clone to give sonar all the info it needs
  GIT_DEPTH: 1000
  # Disable dotnet first time experience
  DOTNET_NOLOGO: true
  # Disable Husky in dotnet tools restore
  HUSKY: 0

workflow:
  rules:
    # Avoid duplicate pipelines in merges
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # Skip pipeline on Publish packages, version bump commits
    - if: $CI_COMMIT_TITLE =~ /Publish packages, version bump/
      when: never
    # Detect source branch name in few scenarios
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - if: $CI_COMMIT_BRANCH
      variables:
        SOURCE_BRANCH: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE =~ /web/
      variables:
        SOURCE_BRANCH: $CI_COMMIT_BRANCH

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  before_script:
    - dotnet tool install versionize --tool-path .tools || true
    - git config user.email "noreply@rapidsoft.ru"
    - git config user.name "Gitlab Runner"
    - echo "Source branch ${SOURCE_BRANCH}"
    - git remote set-url origin  "https://$CI_PROJECT_NAME:$CI_PROJECT_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git fetch --depth=1000 --tags origin $SOURCE_BRANCH
    - git switch $SOURCE_BRANCH
    - 'echo "Collecting change log and bumping version on branch: $SOURCE_BRANCH"'
    - 'echo "Tags collected:"'
    - git tag --list 'v*'
    # Set SemVer suffix based on branch name
    - |
      if [[ "$CI_PIPELINE_SOURCE" == "merge_request_event" && "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "master" ]]; then
        SEMVER_SUFFIX="rc"
      elif [[ "$SOURCE_BRANCH" == release* ]]; then
        SEMVER_SUFFIX="rc"
      elif [[ "$SOURCE_BRANCH" == "develop" ]]; then
        SEMVER_SUFFIX="develop"
      else
        SEMVER_SUFFIX="alpha.$(echo "$SOURCE_BRANCH" | tr '[:upper:]' '[:lower:]' | tr '/+' '-')"
      fi
    - 'echo "SemVer pre-release suffix: $SEMVER_SUFFIX"'
    - |
      if [ "$SOURCE_BRANCH" = "master" ]; then
        echo "Upgrading to release version"
        .tools/versionize --aggregate-pre-releases 
      else
        echo "Upgrading to pre-release version in branch $SOURCE_BRANCH"
        .tools/versionize --pre-release "$SEMVER_SUFFIX"
      fi
  script:
    - echo "Building solution"
    - dotnet build --packages .nuget/packages/ -c Release
    - dotnet pack --no-build -c Release -o $NUPKG_FOLDER --include-symbols --include-source

    - echo "Pushing version changes to GIT"
    - git add **/*.csproj
    - |
      if [ "$SOURCE_BRANCH" = "master" ]; then
        echo "Adding CHANGELOG.md to git"
        git add CHANGELOG.md
      fi
    - |
      if git diff-index --quiet HEAD --; then
        echo "No changes to commit"
      else
        git commit --no-verify -m "Publish packages, version bump"
      fi
    - git push --follow-tags origin $SOURCE_BRANCH -o ci.skip
  cache:
    key: dotnet-packages-cache
    paths:
      - .nuget/packages/
      - .tools/
    unprotect: true
  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - "$NUPKG_FOLDER/"

test_job:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  services:
    - name: mysql/mysql-server
      alias: localmysql
    - name: postgres
      alias: localpostgres
    - name: mcr.microsoft.com/azure-sql-edge
      alias: localmssql
    - name: clickhouse/clickhouse-server
      alias: localclickhouse
    - name: krisgeus/docker-kafka
      alias: kafka
    - name: docker:24.0.5-dind
      alias: docker
      command: [ "dockerd", "--tls=false", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock" ]
  variables:
    DOCKER_HOST: tcp://docker:2375
    # MySQL image customization
    MYSQL_ROOT_HOST: '%'
    MYSQL_ROOT_PASSWORD: 'etlboxpassword'
    # MYSQL_USER: , MYSQL_PASSWORD

    # Postgres image customization
    POSTGRES_PASSWORD: 'etlboxpassword'

    # MS SQL image customization
    ACCEPT_EULA: 'Y'
    SA_PASSWORD: 'YourStrong@Passw0rd'
    MSSQL_PID: 'Developer'
    # CLICKHOUSE image customization
    CLICKHOUSE_USER: clickhouse
    CLICKHOUSE_PASSWORD: Qwe123456
    CLICKHOUSE_MAX_CONNECTIONS: 100
    # KAFKA customization
    ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,INTERNAL://localhost:9093'
    LISTENERS: 'PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093'
    SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
    INTER_BROKER: 'INTERNAL'
    KAFKA_CREATE_TOPICS: 'cc-event:36:1'

  before_script:
    - pushd test
    - pwsh ./Set-Configuration.ps1 gitlab-ci
    - popd
    - dotnet tool install dotnet-reportgenerator-globaltool --tool-path .tools || true
    - dotnet build --packages .nuget/packages/ -c Release
  script:
    - >
      dotnet test --no-build --configuration=Release --filter="Category!=Performance" --logger="console;verbosity=detailed"
      --logger="junit;LogFilePath=../artifacts/{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
      --collect="XPlat Code Coverage"
  after_script:
    - .tools/reportgenerator "-reports:./**/*.cobertura.xml" "-targetdir:.coverage" -reportTypes:TextSummary
    - cat .coverage/Summary.txt
    - echo 'End Summary'
  coverage: /Line coverage:[\s\S].+%/
  cache:
    key: dotnet-packages-cache
    paths:
      - .nuget/packages/
      - .tools/
    unprotect: true
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
      coverage_report:
        coverage_format: cobertura
        path: ./**/coverage.cobertura.xml

publish:internal:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo "Publishing version internally to $NUGET_SOURCE"
    - dotnet nuget push "$NUPKG_FOLDER/*.nupkg" --source $NUGET_SOURCE --api-key $NUGET_API_KEY
  needs:
    - build_job
    - test_job

publish:nuget-org:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo "Publishing version to nuget.org..."
    - dotnet nuget push "$NUPKG_FOLDER/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_ORG_API_KEY
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ( $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ )
      when: manual
  needs:
    - build_job
    - test_job
