#file: noinspection CIAidGitLabYamlNeedsJobUnavailable - This is needed for an external job `get_unique_semversion`
include:
  # GitVersion component
  - component: $CI_SERVER_FQDN/open-source/ci-components/ultimate-auto-semversioning@0.1.5

variables:
  # Opt out of telemetry (turbo and others), see https://consoledonottrack.com/
  DO_NOT_TRACK: 1
  # Enable debug services
  CI_DEBUG_SERVICES: 'true'
  # Enable service network
  FF_NETWORK_PER_BUILD: 'true'
  # Nupkg folder
  NUPKG_FOLDER: '.packages'
  NUGET_SOURCE: https://nuget.rapidsoft.ru/nuget/Rapidsoft-Nuget/v3/index.json
  NUGETORG_SOURCE: https://api.nuget.org/v3/index.json
  # All console out of dotnet should be in English
  LANG: C
  LCID: 1033
  # Disable dotnet first time experience
  DOTNET_NOLOGO: true
  # Disable Husky in dotnet tools restore
  HUSKY: 0

workflow:
  rules:
    # Run for merge request commits
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Avoid duplicates for merge requests
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # Launch for any branch commit
    - if: $CI_COMMIT_BRANCH
    # Launch for properly formatted version tags
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/

default:
  image: mcr.microsoft.com/dotnet/sdk:8.0

build_job:
  needs:
    - get_unique_semversion
  variables:
    PACKAGE_VERSION: ${GitVersion_SemVer}
  script:
    - echo "Building version $PACKAGE_VERSION"
    - dotnet build --packages .nuget/packages/ -c Release -p:Version=$PACKAGE_VERSION
    - dotnet pack --no-build -c Release -p:Version=$PACKAGE_VERSION -o $NUPKG_FOLDER --include-symbols --include-source
  artifacts:
    expire_in: 1 week # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - '$NUPKG_FOLDER/'

test_job:
  needs:
    - get_unique_semversion
  services:
    - name: mysql/mysql-server
      alias: localmysql
      variables:
        MYSQL_ROOT_HOST: '%'
        MYSQL_ROOT_PASSWORD: 'etlboxpassword'
    - name: postgres
      alias: localpostgres
      variables:
        POSTGRES_PASSWORD: 'etlboxpassword'
        LANG: en_US.utf8
    - name: mcr.microsoft.com/azure-sql-edge
      alias: localmssql
      variables:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'YourStrong@Passw0rd'
        MSSQL_PID: 'Developer'
    - name: clickhouse/clickhouse-server
      alias: localclickhouse
      variables:
        CLICKHOUSE_USER: clickhouse
        CLICKHOUSE_PASSWORD: Qwe123456
        CLICKHOUSE_MAX_CONNECTIONS: 100
    - name: apache/kafka:latest
      alias: kafka
      variables:
        KAFKA_NODE_ID: '1'
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
        KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
        CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    - name: docker:24.0.5-dind
      alias: docker
      command:
        [
          'dockerd',
          '--tls=false',
          '--host=tcp://0.0.0.0:2375',
          '--host=unix:///var/run/docker.sock',
        ]
  variables:
    DOCKER_HOST: tcp://docker:2375
    PACKAGE_VERSION: ${GitVersion_SemVer}
  before_script:
    - pushd test
    - pwsh ./Set-Configuration.ps1 gitlab-ci
    - popd
    - dotnet tool install dotnet-reportgenerator-globaltool --tool-path .tools || true
    - dotnet build --packages .nuget/packages/ -c Release -p:Version=$PACKAGE_VERSION
  script:
    - >
      dotnet test --no-build --configuration=Release --filter="Category!=Performance" --logger="console;verbosity=detailed"
      --logger="junit;LogFilePath=../artifacts/{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
      --collect="XPlat Code Coverage"
  after_script:
    - .tools/reportgenerator "-reports:./**/*.cobertura.xml" "-targetdir:.coverage" -reportTypes:TextSummary
    - cat .coverage/Summary.txt
    - echo 'End Summary'
  coverage: /Line coverage:[\s\S].+%/
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
      coverage_report:
        coverage_format: cobertura
        path: ./**/coverage.cobertura.xml

publish:internal:
  needs:
    - get_unique_semversion
    - build_job
    - test_job
  variables:
    PACKAGE_VERSION: ${GitVersion_SemVer}
  script:
    - echo "Publishing version $PACKAGE_VERSION internally to $NUGET_SOURCE"
    - dotnet nuget push "$NUPKG_FOLDER/*.nupkg" --source $NUGET_SOURCE --api-key $NUGET_API_KEY

# Please see [Release CI/CD examples](https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html) for many rich examples for triggering a release only on specific conditions.
release_job:
  needs:
    - get_unique_semversion
    - build_job
    - test_job
  image: registry.gitlab.com/gitlab-org/cli:latest
  variables:
    RELEASE_VERSION: ${GitVersion_MajorMinorPatch}
  rules:
    # Allow manual release at any protected branch
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED != "false"'
      when: manual
  script:
    - echo "running release_job for version $RELEASE_VERSION"
  release:
    # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: $RELEASE_VERSION
    description: $RELEASE_VERSION

publish:nuget-org:
  needs:
    - get_unique_semversion
    - build_job
    - test_job
  variables:
    PACKAGE_VERSION: ${GitVersion_SemVer}
  interruptible: true
  script:
    - echo "Publishing version $PACKAGE_VERSION to nuget.org..."
    - dotnet nuget push "$NUPKG_FOLDER/*.nupkg" --source $NUGETORG_SOURCE --api-key $NUGET_ORG_API_KEY
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
      when: manual

pages:
  needs:
    - get_unique_semversion
    - build_job
  variables:
    PACKAGE_VERSION: ${GitVersion_SemVer}
  script:
    - dotnet tool restore
    - dotnet docfx docfx/docfx.json
    - mv _site public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    # Allow manual docs generation on any branch
    - if: $CI_COMMIT_BRANCH != "master"
      when: manual
