# place project specific paths in variables to make the rest of the script more generic
variables:
  NUPKG_FOLDER: 'ETLBox/bin/Release/'

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet build ETLBox.sln -c Release
  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - "$NUPKG_FOLDER/"

test_job:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  services:
    - name: mysql/mysql-server
      alias: localmysql
    - name: postgres
      alias: localpostgres
    - name: mcr.microsoft.com/mssql/server
      alias: localmssql
  variables:
    # MySQL image customization
    MYSQL_ROOT_HOST: '%'
    MYSQL_ROOT_PASSWORD: 'etlboxpassword'
    # MYSQL_USER: , MYSQL_PASSWORD

    # Postgres image customization
    POSTGRES_PASSWORD: 'etlboxpassword'

    # MS SQL image customization
    ACCEPT_EULA: 'Y'
    SA_PASSWORD: 'YourStrong@Passw0rd'
    MSSQL_PID: 'Developer'

    # dotnet settings
    DOT_NET_TEST_OPTIONS: '-c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --filter "Category!=Performance"'
  before_script:
    # mysql -uroot -petlboxpassword

    # ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'etlboxpassword';
    # ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'etlboxpassword';
    # FLUSH PRIVILEGES;

  script:
    - pushd test
    - pwsh ./Set-Configuration.ps1 gitlab-ci
    - popd
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestConnectionManager
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestControlFlowTasks
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestDatabaseConnectors
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestFlatFileConnectors
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestHelper
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestNonParallel
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestOtherConnectors
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestPerformance
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestShared
    - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestTransformations