stages:
  - build
  - test

build_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    NUPKG_FOLDER: 'ETLBox/bin/Release/'
  script:
    - dotnet build ETLBox.sln -c Release
  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - "$NUPKG_FOLDER/"
  rules:
    - if: $CI_COMMIT_TAG

sonarqube-check:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:latest
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
      - "apt-get update"
      - "apt-get install --yes openjdk-11-jre"
      - "dotnet tool install --global dotnet-sonarscanner"
      - "export PATH=\"$PATH:$HOME/.dotnet/tools\""
      - "dotnet sonarscanner begin /k:\"open-source_etlbox_AX2rV2MSOqMd9uKUCs_O\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
      - "dotnet build"
      - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true      

test_job:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  services:
    - name: mysql/mysql-server
      alias: localmysql
    - name: postgres
      alias: localpostgres
    - name: hub.rapidsoft.ru/open-source/mssql-docker:latest
      alias: localmssql
  variables:
    # MySQL image customization
    MYSQL_ROOT_HOST: '%'
    MYSQL_ROOT_PASSWORD: 'etlboxpassword'
    # MYSQL_USER: , MYSQL_PASSWORD

    # Postgres image customization
    POSTGRES_PASSWORD: 'etlboxpassword'

    # MS SQL image customization
    ACCEPT_EULA: 'Y'
    SA_PASSWORD: 'YourStrong@Passw0rd'
    MSSQL_PID: 'Developer'

    # dotnet settings
    DOT_NET_TEST_OPTIONS: '-c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --filter "Category!=Performance"'
  before_script:
    # mysql -uroot -petlboxpassword

    # ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'etlboxpassword';
    # ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'etlboxpassword';
    # FLUSH PRIVILEGES;

  script:
    - pushd test
    - pwsh ./Set-Configuration.ps1 gitlab-ci
    - popd
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestConnectionManager
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestControlFlowTasks
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestDatabaseConnectors
    - pushd ./TestFlatFileConnectors; dotnet test ${DOT_NET_TEST_OPTIONS} .; popd
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestHelper
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestNonParallel
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestOtherConnectors
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestPerformance
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestShared
    # - dotnet test ${DOT_NET_TEST_OPTIONS} ./TestTransformations
  rules:
    - if: $CI_COMMIT_TAG
